name: indonesian_timezone
description: To make it easier to convert time into the form of Indonesian time zones (WIB, WITA, & WIT)
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  intl:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
